- name: deploy WordPress Nginx virtual host
  template:
    src: nginx.j2
    dest: "{{ compose_project_dir }}/{{ project.dir }}/nginx/wordpress.conf"
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0644
