---
# setup compose dir structure
- name: setup compose dir structure and required files
  include_tasks: directory.yml
  loop: "{{ projects }}"
  loop_control:
    loop_var: project
  tags:
    - dir_ops
# - name: create docker-compose.yml file
#   file:
#     path: "{{ compose_project_dir }}/docker-compose.yml"
#     owner: "{{ system_user }}"
#     group: "{{ system_user }}"
#     state: touch
#   tags:
#     - file_ops

# - name: deploy Docker Compose project for (Wordpress/MariaDB/Nginx containers)
#   template:
#     src: docker-compose.j2
#     dest: "{{ compose_project_dir }}/docker-compose.yml"
#     owner: "{{ system_user }}"
#     group: "{{ system_user }}"
#     mode: 0644
#   with_items:
#     - sites
#   tags:
#     - deploy_compose

# - name: Run docker-compose up
#   command: docker-compose -f docker-compose.yml up -d
#   args:
#     chdir: "{{ compose_project_dir }}"
#   tags:
#     - compose_run

# - name: giving some time for project (all 3 containers) to start-up
#   pause:
#     seconds: 10

# # debug output
# - debug:
#     msg:
#       - "With specified variables, following configuration has been made:"
#       - ""
#       - "URL used for Nginx virtual host: {{ domain }}"
#       - "WordPress Docker image version:{{ wp_version }}-php8.1-fpm"
#       - "WORDPRESS_DB_NAME: {{ wp_db_name }}"
#       - "WORDPRESS_DB_USER: {{ wp_db_user }}"
#       - "WORDPRESS_TABLE_PREFIX: {{ wp_db_tb_pre }}"
#       - "WORDPRESS_DB_HOST: {{ wp_db_host }}"
#       - "WORDPRESS_DB_PASSWORD: {{ wp_db_psw }}"
#       - "MYSQL_ROOT_PASSWORD: {{ wp_db_psw }}"

# - debug:
#     msg:
#       - "Setup successfully complete."
#       - ""
#       - "Wordpress instance is available on following IP: {{ inventory_hostname }}"
#       - "If DNS is pointing to this IP, it'll be available on: {{ domain }}"
#   tags:
#     - result
