---
# setup compose dir structure
- name: setup compose dir structure
  file:
    path: "{{ compose_project_dir }}/{{ item }}"
    state: directory
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    recurse: yes
    mode: 0755
  with_items:
    - nginx
    - logs/nginx
  tags:
    - dir_ops

- name: create docker-compose-nginx.yml file
  file:
    path: "{{ compose_project_dir }}/docker-compose-nginx.yml"
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    state: touch
  tags:
    - file_ops

- name: deploy Docker Compose project for (Wordpress/MariaDB/Nginx containers)
  template:
    src: docker-compose-nginx.j2
    dest: "{{ compose_project_dir }}/docker-compose-nginx.yml"
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0644
  tags:
    - deploy_compose_nginx

- name: deploy WordPress Nginx virtual host
  template:
    src: wordpress-nginx.j2
    dest: "{{ compose_project_dir }}/nginx/wordpress-{{ domain }}.conf"
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0644
  tags:
    - gen_nginx

- name: Run docker-compose up
  command: docker-compose -f docker-compose-nginx.yml up -d --remove-orphans
  args:
    chdir: "{{ compose_project_dir }}"
  tags:
    - compose_run_nginx

- name: giving some time for project (all 3 containers) to start-up
  pause:
    seconds: 10

# debug output
- debug:
    msg:
      - "With specified variables, following configuration has been made:"
      - ""
      - "URL used for Nginx virtual host: {{ domain }}"
