---
- hosts: wordpress

  vars_files:
    - defaults/main.yml

  remote_user: "{{ system_user }}"
  become: yes
  gather_facts: no
  serial: 1

  vars_prompt:

    # - name: domain
    #   prompt: "\n------
    #           \n\nSpecify WordPress URL"
    #   private: no
    #   default: "365code.in"

    # - name: wp_version
    #   prompt: "\n------
    #           \n\nSpecify WordPress version you'd like to use"
    #   private: no
    #   default: "6.6.2"

    # - name: wp_db_name
    #   prompt: "\n------
    #           \n\nSpecify WordPress database name"
    #   private: no
    #   default: "wordpress"

    # - name: wp_db_tb_pre
    #   prompt: "\n------
    #           \n\nSpecify WordPress table prefix"
    #   private: no
    #   default: "wp_"

    # - name: wp_db_psw
    #   prompt: "\n------
    #           \n\nSpecify WordPress database password"
    #   private: yes
    #   default: "C7@kM3"
    #   confirm: yes

  roles:
    # - python
    # - mariadb
    # - docker
    - nginx
    # - wordpress
